name: (dev) [ms] Deploy to Cloudflare Worker

on:
  push:
    branches:
      - dev
    paths:
      - 'backend-main/**'
      - '.github/workflows/ms-dev.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install project dependencies
        run: cd backend-main && npm install

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Update wrangler config with environment variables && Update name to append dev1
        run: |
          cd backend-domain-ms
          # Update wrangler.jsonc with environment variables using sed
          sed -i "s|\"database_id\":[[:space:]]*\"[^\"]*\"|\"database_id\": \"${{ vars.CLOUDFLARE_D1_DATABASE_ID }}\"|g" wrangler.jsonc
          
          # Update project name to include -dev suffix
          sed -i 's/"name": "\([^"]*\)"/"name": "\1-dev"/' wrangler.jsonc

          echo "Successfully updated wrangler.jsonc with environment variables"

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          cd backend-domain-ms
          cat wrangler.jsonc && cat wrangler.jsonc >> wrangler.local.jsonc
          wrangler deploy --config wrangler.local.jsonc

